import { DatingProfile } from "../components/TinderCard";

export const mockProfiles: DatingProfile[] = [
  // ─── ESPAÑA (6 Chicas) ──────────────────────────────────────────
  {
    id: "mock-es-01",
    firstName: "Alejandra",
    lastName: "Morales",
    age: 27,
    gender: "FEMALE",
    country: "España",
    city: "Sevilla",
    languages: ["es", "en"],
    profession: "Arquitecta de Interiores",
    maritalStatus: "Single",
    bio: "Apasionada por el diseño mediterráneo y los atardeceres frente al mar. Busco a alguien especial con quien reír, conversar de todo y planear viajes espontáneos.",
    interests: ["Diseño", "Yoga", "Fotografía", "Vino", "Viajes"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-es-02",
    firstName: "Lucía",
    lastName: "Fernández",
    age: 25,
    gender: "FEMALE",
    country: "España",
    city: "Madrid",
    languages: ["es", "en", "fr"],
    profession: "Periodista de Moda",
    maritalStatus: "Single",
    bio: "Amante del café de especialidad y los mercadillos vintage. Escribir y viajar me llenan la vida. ¿Nos tomamos un café y compartimos historias?",
    interests: ["Música", "Moda", "Fotografía", "Lectura", "Café"],
    height: 165,
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-es-03",
    firstName: "Sofía",
    lastName: "Castro",
    age: 29,
    gender: "FEMALE",
    country: "España",
    city: "Barcelona",
    languages: ["es", "en", "ca"],
    profession: "Bióloga Marina",
    maritalStatus: "Single",
    bio: "Naturaleza, buceo y libros. El mar es mi hogar espiritual. Busco una conexión real con alguien auténtico que también ame la aventura.",
    interests: ["Ciencia", "Buceo", "Senderismo", "Viajes", "Cine"],
    height: 170,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-es-04",
    firstName: "Carmen",
    lastName: "Pérez",
    age: 31,
    gender: "FEMALE",
    country: "España",
    city: "Valencia",
    languages: ["es", "en"],
    profession: "Fisioterapeuta",
    maritalStatus: "Single",
    bio: "Activa, alegre y un poco aventurera. Me encanta el deporte al aire libre y la comida saludable, pero nunca le digo que no a una buena pizza.",
    interests: ["Deporte", "Cocina", "Playa", "Pilates", "Música"],
    height: 166,
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    verified: false,
    lookingFor: "friendship",
  },
  {
    id: "mock-es-05",
    firstName: "Elena",
    lastName: "Ortiz",
    age: 28,
    gender: "FEMALE",
    country: "España",
    city: "Málaga",
    languages: ["es", "en"],
    profession: "Diseñadora Gráfica",
    maritalStatus: "Single",
    bio: "Creativa de mente inquieta. Me encanta la ilustración, los perros y salir a correr por la playa. Busco a alguien con sentido del humor.",
    interests: ["Ilustración", "Arte", "Mascotas", "Running", "Playas"],
    height: 164,
    imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-es-06",
    firstName: "María",
    lastName: "Vargas",
    age: 26,
    gender: "FEMALE",
    country: "España",
    city: "Zaragoza",
    languages: ["es", "en"],
    profession: "Maestra de Primaria",
    maritalStatus: "Single",
    bio: "Me encanta enseñar y pasar tiempo en la naturaleza. Busco una relación estable basada en el respeto, el crecimiento mutuo y muchas risas.",
    interests: ["Educación", "Senderismo", "Cine", "Repostería", "Libros"],
    height: 167,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },

  // ─── RUSIA (7 Chicas) ──────────────────────────────────────────
  {
    id: "mock-ru-01",
    firstName: "Anastasia",
    lastName: "Volkova",
    age: 24,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Bailarina Clásica",
    maritalStatus: "Single",
    bio: "Bailarina clásica apasionada por la cultura española y el flamenco. Busco a alguien inteligente con quien explorar el mundo y compartir metas.",
    interests: ["Ballet", "Teatro", "Viajes", "Pintura", "Español"],
    height: 163,
    imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ru-02",
    firstName: "Ekaterina",
    lastName: "Sokolova",
    age: 28,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Traductora de Idiomas",
    maritalStatus: "Single",
    bio: "Me encantan la literatura, el piano y caminar por los parques históricos de Moscú. Busco a una persona con buen corazón e intereses culturales.",
    interests: ["Piano", "Literatura", "Historia", "Idiomas", "Té"],
    height: 169,
    imageUrl: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ru-03",
    firstName: "Natalia",
    lastName: "Kozlova",
    age: 30,
    gender: "FEMALE",
    country: "Rusia",
    city: "Sochi",
    languages: ["ru", "en", "es"],
    profession: "Diseñadora de Moda",
    maritalStatus: "Single",
    bio: "Sochi es donde el mar se encuentra con la montaña. Me encanta esquiar en invierno y nadar en verano. Busco a alguien con mentalidad ganadora.",
    interests: ["Moda", "Esquí", "Mar", "Fitness", "Viajes"],
    height: 172,
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "marriage",
  },
  {
    id: "mock-ru-04",
    firstName: "Sofia",
    lastName: "Petrova",
    age: 26,
    gender: "FEMALE",
    country: "Rusia",
    city: "Kazán",
    languages: ["ru", "en"],
    profession: "Fotógrafa",
    maritalStatus: "Single",
    bio: "Capturo momentos a través de mi lente. Me gusta el té matcha, el jazz y descubrir cafeterías secretas. Hagamos una sesión de fotos y hablemos.",
    interests: ["Fotografía", "Jazz", "Café", "Arte", "Viajes"],
    height: 170,
    imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80",
    verified: false,
    lookingFor: "cultural",
  },
  {
    id: "mock-ru-05",
    firstName: "Olga",
    lastName: "Ivanova",
    age: 27,
    gender: "FEMALE",
    country: "Rusia",
    city: "Novosibirsk",
    languages: ["ru", "en"],
    profession: "Científica de Datos",
    maritalStatus: "Single",
    bio: "Trabajo analizando patrones, pero el amor no sigue algoritmos. Me gusta la física teórica, cocinar platos tradicionales y los gatos.",
    interests: ["Ciencia", "Cocina", "Gatos", "Lectura", "Ajedrez"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1520597204612-a4e9ad4efcf9?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ru-06",
    firstName: "Elena",
    lastName: "Kuznetsova",
    age: 29,
    gender: "FEMALE",
    country: "Rusia",
    city: "Yekaterinburgo",
    languages: ["ru", "en", "es"],
    profession: "Profesora de Música",
    maritalStatus: "Single",
    bio: "Enseño violín a niños y toco en una orquesta filarmónica. Busco a alguien maduro, cariñoso y con buen oído para componer una historia juntos.",
    interests: ["Violín", "Música Clásica", "Conciertos", "Idiomas", "Teatro"],
    height: 167,
    imageUrl: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ru-07",
    firstName: "Daria",
    lastName: "Morozova",
    age: 25,
    gender: "FEMALE",
    country: "Rusia",
    city: "Vladivostok",
    languages: ["ru", "en"],
    profession: "Guía Turística",
    maritalStatus: "Single",
    bio: "Vladivostok tiene puentes maravillosos y mar. Me apasiona enseñar mi ciudad a viajeros. Quiero viajar a España muy pronto. ¿Me enseñas tu país?",
    interests: ["Viajes", "Senderismo", "Idiomas", "Mariscos", "Fotografía"],
    height: 171,
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "cultural",
  },

  // ─── LETONIA (7 Chicas) ────────────────────────────────────────
  {
    id: "mock-lv-01",
    firstName: "Liga",
    lastName: "Berzina",
    age: 26,
    gender: "FEMALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "ru", "es"],
    profession: "Traductora de Documentos",
    maritalStatus: "Single",
    bio: "Riga es una ciudad medieval de cuento, pero mi corazón anhela el calor del Mediterráneo. Busco un novio con alma de aventurero.",
    interests: ["Idiomas", "Viajes", "Senderismo", "Vela", "Cocina"],
    height: 171,
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-lv-02",
    firstName: "Marta",
    lastName: "Ozola",
    age: 23,
    gender: "FEMALE",
    country: "Letonia",
    city: "Jūrmala",
    languages: ["lv", "ru", "en"],
    profession: "Estudiante de Diseño",
    maritalStatus: "Single",
    bio: "Jūrmala tiene playas de arena blanca increíbles. Me encanta la arcilla, la pintura y el paddle surf. Hagamos planes sencillos frente al mar.",
    interests: ["Cerámica", "Surf", "Diseño", "Playas", "Fotografía"],
    height: 165,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "friendship",
  },
  {
    id: "mock-lv-03",
    firstName: "Ilze",
    lastName: "Vitola",
    age: 35,
    gender: "FEMALE",
    country: "Letonia",
    city: "Liepāja",
    languages: ["lv", "en", "ru"],
    profession: "Médica Pediatra",
    maritalStatus: "Single",
    bio: "Disfruto del viento de Liepāja, la lectura clásica y la meditación junto al mar. Busco una relación seria y honesta para formar un hogar.",
    interests: ["Medicina", "Yoga", "Lectura", "Caminatas", "Cocina"],
    height: 167,
    imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "marriage",
  },
  {
    id: "mock-lv-04",
    firstName: "Laura",
    lastName: "Kalnina",
    age: 27,
    gender: "FEMALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "es"],
    profession: "Diseñadora de UX",
    maritalStatus: "Single",
    bio: "UX de día, ciclista de fin de semana. Aprendiendo español. Me encanta bailar salsa y la comida picante. Busco intercambios y quizás algo más.",
    interests: ["UX", "Ciclismo", "Salsa", "Viajes", "Idiomas"],
    height: 169,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-lv-05",
    firstName: "Zane",
    lastName: "Krumina",
    age: 29,
    gender: "FEMALE",
    country: "Letonia",
    city: "Sigulda",
    languages: ["lv", "en", "ru"],
    profession: "Florista",
    maritalStatus: "Single",
    bio: "Sigulda tiene castillos y mucha naturaleza. Trabajo rodeada de flores. Amante del senderismo de montaña y los picnics. Busco a alguien romántico.",
    interests: ["Flores", "Senderismo", "Montaña", "Picnics", "Camping"],
    height: 172,
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    verified: false,
    lookingFor: "relationship",
  },
  {
    id: "mock-lv-06",
    firstName: "Kristine",
    lastName: "Liepina",
    age: 31,
    gender: "FEMALE",
    country: "Letonia",
    city: "Ventspils",
    languages: ["lv", "en", "de"],
    profession: "Ingeniera Química",
    maritalStatus: "Single",
    bio: "Investigadora en desarrollo de cosmética natural. Me gusta el teatro, patinar sobre hielo y cocinar postres. Busco a alguien maduro y divertido.",
    interests: ["Teatro", "Patinaje", "Repostería", "Cosmética", "Cine"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-lv-07",
    firstName: "Anete",
    lastName: "Eglite",
    age: 25,
    gender: "FEMALE",
    country: "Letonia",
    city: "Valmiera",
    languages: ["lv", "en"],
    profession: "Entrenadora de Tenis",
    maritalStatus: "Single",
    bio: "El deporte es mi vida. Me gusta el tenis, el fitness y los perros grandes. Soy muy enérgica y optimista. Busco un compañero con estilo de vida saludable.",
    interests: ["Tenis", "Fitness", "Perros", "Nutrición", "Música"],
    height: 173,
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  // ─── EXTRA PREMIUM PROFILES (20 Chicas) ─────────────────────────
  {
    id: "mock-ext-01",
    firstName: "Irina",
    lastName: "Smirnova",
    age: 26,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Directora de Marketing",
    maritalStatus: "Single",
    bio: "Apasionada por la moda, los viajes exóticos y la comida mediterránea. Busco una relación seria con un hombre inteligente, aventurero y con buen corazón.",
    interests: ["Marketing", "Moda", "Viajes", "Vino", "Fitness"],
    height: 170,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-02",
    firstName: "Ksenia",
    lastName: "Popova",
    age: 28,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Diseñadora Gráfica",
    maritalStatus: "Single",
    bio: "Me encanta la pintura, el café espresso por las mañanas y pasear por los canales. Aprendiendo español. Busco amigos o algo más.",
    interests: ["Arte", "Diseño", "Café", "Senderismo", "Español"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-03",
    firstName: "Alisa",
    lastName: "Sokolova",
    age: 24,
    gender: "FEMALE",
    country: "Rusia",
    city: "Sochi",
    languages: ["ru", "en"],
    profession: "Entrenadora de Fitness",
    maritalStatus: "Single",
    bio: "Adicta al sol, la playa y el deporte. Me gusta el snowboard en invierno y el surf en verano. Busco a alguien activo y divertido para compartir aventuras.",
    interests: ["Deporte", "Playas", "Fitness", "Viajes", "Música"],
    height: 165,
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-04",
    firstName: "Daria",
    lastName: "Vasilieva",
    age: 29,
    gender: "FEMALE",
    country: "Rusia",
    city: "Kazán",
    languages: ["ru", "en", "es"],
    profession: "Periodista",
    maritalStatus: "Single",
    bio: "Curiosa por naturaleza. Me encanta escribir historias, leer buena literatura y bailar salsa. Busco una conexión profunda y honesta.",
    interests: ["Lectura", "Salsa", "Cine", "Fotografía", "Idiomas"],
    height: 172,
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-05",
    firstName: "Polina",
    lastName: "Nikolaeva",
    age: 25,
    gender: "FEMALE",
    country: "Rusia",
    city: "Novosibirsk",
    languages: ["ru", "en"],
    profession: "Fotógrafa Profesional",
    maritalStatus: "Single",
    bio: "Capturando la belleza en las cosas simples. Amo los atardeceres, el té matcha y la música clásica. ¿Hacemos una sesión de fotos?",
    interests: ["Fotografía", "Música", "Viajes", "Arte", "Té"],
    height: 169,
    imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80",
    verified: false,
    lookingFor: "cultural",
  },
  {
    id: "mock-ext-06",
    firstName: "Marina",
    lastName: "Kozlova",
    age: 27,
    gender: "FEMALE",
    country: "Rusia",
    city: "Vladivostok",
    languages: ["ru", "en"],
    profession: "Bióloga",
    maritalStatus: "Single",
    bio: "El océano es mi mayor pasión. Me encanta bucear, acampar y la naturaleza salvaje. Busco una mente científica y aventurera.",
    interests: ["Ciencia", "Buceo", "Acampada", "Senderismo", "Mascotas"],
    height: 167,
    imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-07",
    firstName: "Julia",
    lastName: "Morozova",
    age: 30,
    gender: "FEMALE",
    country: "Rusia",
    city: "Yekaterinburgo",
    languages: ["ru", "en"],
    profession: "Arquitecta",
    maritalStatus: "Single",
    bio: "Diseñadora de espacios urbanos. Amante de la buena arquitectura, el piano y la cocina gourmet. Busco estabilidad, lealtad y amor sincero.",
    interests: ["Diseño", "Piano", "Cocina", "Historia", "Viajes"],
    height: 171,
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "marriage",
  },
  {
    id: "mock-ext-08",
    firstName: "Natalia",
    lastName: "Orlova",
    age: 23,
    gender: "FEMALE",
    country: "Rusia",
    city: "Rostov",
    languages: ["ru", "en", "es"],
    profession: "Estudiante de Medicina",
    maritalStatus: "Single",
    bio: "Futura pediatra. Me encantan los niños, los animales y salir a correr por las mañanas. Muy optimista y alegre. ¿Hablamos?",
    interests: ["Medicina", "Running", "Mascotas", "Cine", "Música"],
    height: 166,
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-09",
    firstName: "Anna",
    lastName: "Kuznetsova",
    age: 26,
    gender: "FEMALE",
    country: "Rusia",
    city: "Krasnodar",
    languages: ["ru", "en"],
    profession: "Florista",
    maritalStatus: "Single",
    bio: "Rodeada de flores y colores. Me encanta la decoración, los picnics los domingos y los paseos en bicicleta. Busco un chico dulce y detallista.",
    interests: ["Flores", "Picnics", "Ciclismo", "Moda", "Fotografía"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-10",
    firstName: "Olga",
    lastName: "Pavlova",
    age: 28,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Traductora",
    maritalStatus: "Single",
    bio: "Hablo tres idiomas pero busco el lenguaje del amor. Amante de la ópera, los museos y viajar a lugares con historia. Busco a alguien maduro.",
    interests: ["Idiomas", "Teatro", "Historia", "Viajes", "Lectura"],
    height: 173,
    imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-11",
    firstName: "Sofia",
    lastName: "Sokolova",
    age: 25,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Diseñadora de Moda",
    maritalStatus: "Single",
    bio: "Creando mi propia marca de ropa. Me encanta el diseño de moda, los desfiles y el ballet clásico. Busco inspiración y una conexión real.",
    interests: ["Moda", "Ballet", "Arte", "Diseño", "Música"],
    height: 170,
    imageUrl: "https://images.unsplash.com/photo-1520597204612-a4e9ad4efcf9?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-12",
    firstName: "Victoria",
    lastName: "Novikova",
    age: 27,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Ingeniera de Software",
    maritalStatus: "Single",
    bio: "Escribo código de día y toco la guitarra acústica de noche. Me gustan los videojuegos, las series de ciencia ficción y los gatitos. ¿Hacemos un match?",
    interests: ["Tecnología", "Guitarra", "Videojuegos", "Ciencia", "Lectura"],
    height: 172,
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-13",
    firstName: "Valeria",
    lastName: "Berzina",
    age: 24,
    gender: "FEMALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "ru"],
    profession: "Estudiante de Diseño",
    maritalStatus: "Single",
    bio: "Apasionada por el diseño industrial y la cerámica. Disfruto de los picnics junto al río y patinar. Busco a alguien creativo para compartir aficiones.",
    interests: ["Diseño", "Cerámica", "Picnics", "Patinaje", "Música"],
    height: 166,
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-14",
    firstName: "Katia",
    lastName: "Fernández",
    age: 26,
    gender: "FEMALE",
    country: "España",
    city: "Madrid",
    languages: ["es", "en"],
    profession: "Repostera",
    maritalStatus: "Single",
    bio: "El dulce es mi pasión. Hago pasteles de diseño y me encanta la fotografía culinaria. Busco a un chico con buen apetito y sentido del humor.",
    interests: ["Repostería", "Fotografía", "Cocina", "Cine", "Vino"],
    height: 169,
    imageUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-15",
    firstName: "Svetlana",
    lastName: "Egorova",
    age: 29,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Guía de Viajes",
    maritalStatus: "Single",
    bio: "Mi trabajo es enseñar el mundo. Me apasiona viajar, conocer nuevas culturas y aprender idiomas. Mi próximo destino es España. ¿Me acompañas?",
    interests: ["Viajes", "Idiomas", "Fotografía", "Senderismo", "Cine"],
    height: 171,
    imageUrl: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "cultural",
  },
  {
    id: "mock-ext-16",
    firstName: "Tatiana",
    lastName: "Zaitseva",
    age: 25,
    gender: "FEMALE",
    country: "Rusia",
    city: "Sochi",
    languages: ["ru", "en"],
    profession: "Fisioterapeuta",
    maritalStatus: "Single",
    bio: "Me encanta el yoga frente al mar, la comida sana y correr por la playa. Busco a un chico deportista, optimista y con energía positiva.",
    interests: ["Yoga", "Fitness", "Running", "Playas", "Nutrición"],
    height: 167,
    imageUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ext-17",
    firstName: "Maria",
    lastName: "García",
    age: 27,
    gender: "FEMALE",
    country: "España",
    city: "Barcelona",
    languages: ["es", "en", "ru"],
    profession: "Ilustradora Gráfica",
    maritalStatus: "Single",
    bio: "Apasionada del dibujo, los cómics y los gatos. Dibujo cómics románticos pero busco escribir mi propia historia real. Interesada en la cultura rusa.",
    interests: ["Ilustración", "Cómics", "Gatos", "Cine", "Lectura"],
    height: 165,
    imageUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-18",
    firstName: "Veronika",
    lastName: "Kozlova",
    age: 23,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Estudiante de Periodismo",
    maritalStatus: "Single",
    bio: "Apasionada de la radio, la música indie y los festivales. Siempre con ganas de aprender cosas nuevas. Busco un chico auténtico y divertido.",
    interests: ["Periodismo", "Música", "Festivales", "Lectura", "Viajes"],
    height: 168,
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ext-19",
    firstName: "Nina",
    lastName: "Berzina",
    age: 28,
    gender: "FEMALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "ru"],
    profession: "Peluquera",
    maritalStatus: "Single",
    bio: "Me encanta el estilismo de cabello, la moda y el maquillaje. Amo salir con mis amigos, la música pop y las cenas con risas infinitas.",
    interests: ["Moda", "Estilismo", "Música", "Cine", "Cenas"],
    height: 170,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    verified: false,
    lookingFor: "friendship",
  },
  {
    id: "mock-ext-20",
    firstName: "Yulia",
    lastName: "Morozova",
    age: 25,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Bailarina",
    maritalStatus: "Single",
    bio: "Bailarina de danza contemporánea. Me encanta moverme, el teatro y la fotografía urbana. Busco a alguien apasionado del arte.",
    interests: ["Danza", "Teatro", "Fotografía", "Arte", "Viajes"],
    height: 171,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    verified: true,
    lookingFor: "relationship",
  },
];
