import { DatingProfile } from "../components/TinderCard";

// Avatares placeholder usando UI Avatars (texto seguro, sin fotos reales)
const avatar = (name: string, bg: string = "D4A373", color: string = "0A1128") =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=${color}&size=400&bold=true&rounded=false`;

export const mockProfiles: DatingProfile[] = [
  // ─── ESPAÑA ──────────────────────────────────────────────────
  {
    id: "mock-es-01",
    firstName: "Alejandra",
    lastName: "Morales",
    age: 27,
    gender: "FEMALE",
    country: "España",
    city: "Sevilla",
    languages: ["es", "en"],
    profession: "Arquitecta",
    maritalStatus: "Single",
    bio: "Apasionada por el diseño sostenible y los viajes culturales. Busco una conexión genuina con alguien que comparta mi amor por el arte y la historia.",
    interests: ["Arquitectura", "Viajes", "Arte", "Yoga", "Gastronomía"],
    height: 168,
    imageUrl: avatar("Alejandra M", "FF6B8B", "ffffff"),
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-es-02",
    firstName: "Marcos",
    lastName: "Vidal",
    age: 32,
    gender: "MALE",
    country: "España",
    city: "Barcelona",
    languages: ["es", "ca", "en"],
    profession: "Chef",
    maritalStatus: "Single",
    bio: "Chef con estrella Michelin en ciernes. Me encanta compartir recetas mediterráneas y explorar nuevas culturas culinarias. La vida es demasiado corta para comer mal.",
    interests: ["Cocina", "Vino", "Ciclismo", "Fotografía"],
    height: 180,
    imageUrl: avatar("Marcos V", "D4A373", "0A1128"),
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-es-03",
    firstName: "Lucía",
    lastName: "Fernández",
    age: 25,
    gender: "FEMALE",
    country: "España",
    city: "Madrid",
    languages: ["es", "en", "fr"],
    profession: "Periodista",
    maritalStatus: "Single",
    bio: "Cuento historias para vivir. Amante del café de calidad, los libros de segunda mano y las conversaciones que duran hasta el amanecer.",
    interests: ["Periodismo", "Literatura", "Música en vivo", "Café"],
    height: 165,
    imageUrl: avatar("Lucia F", "C084FC", "ffffff"),
    verified: false,
    lookingFor: "friendship",
  },
  {
    id: "mock-es-04",
    firstName: "Diego",
    lastName: "Ruiz",
    age: 30,
    gender: "MALE",
    country: "España",
    city: "Valencia",
    languages: ["es", "en"],
    profession: "Diseñador UX",
    maritalStatus: "Single",
    bio: "Diseño experiencias digitales de día y surfeo por la tarde. Apasionado por el intercambio cultural y aprender idiomas con nativos.",
    interests: ["Diseño", "Surf", "Tecnología", "Idiomas"],
    height: 177,
    imageUrl: avatar("Diego R", "38BDF8", "0A1128"),
    verified: true,
    lookingFor: "cultural",
  },
  {
    id: "mock-es-05",
    firstName: "Sofía",
    lastName: "Castro",
    age: 29,
    gender: "FEMALE",
    country: "España",
    city: "Bilbao",
    languages: ["es", "eu", "en"],
    profession: "Investigadora",
    maritalStatus: "Single",
    bio: "Doctora en biología marina. Fascinada por el mar y las culturas del Este de Europa. Busco un compañero de aventuras con quien crecer.",
    interests: ["Ciencia", "Buceo", "Senderismo", "Rusia"],
    height: 170,
    imageUrl: avatar("Sofia C", "34D399", "0A1128"),
    verified: true,
    lookingFor: "serious",
  },

  // ─── RUSIA ───────────────────────────────────────────────────
  {
    id: "mock-ru-01",
    firstName: "Anastasia",
    lastName: "Volkov",
    age: 24,
    gender: "FEMALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en", "es"],
    profession: "Bailarina",
    maritalStatus: "Single",
    bio: "Bailarina clásica del Teatro Mariinsky. Sueño con vivir en España y absorber su cultura. El flamenco me tiene enamorada.",
    interests: ["Ballet", "Flamenco", "Pintura", "Historia"],
    height: 163,
    imageUrl: avatar("Anastasia V", "FF6B8B", "ffffff"),
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-ru-02",
    firstName: "Mikhail",
    lastName: "Sokolov",
    age: 34,
    gender: "MALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Ingeniero Aeroespacial",
    maritalStatus: "Single",
    bio: "Trabajo en tecnología satelital pero mi pasión es el montañismo. Los Urales en invierno o la Sierra Nevada en verano, da igual con buena compañía.",
    interests: ["Montañismo", "Física", "Ajedrez", "Esquí"],
    height: 186,
    imageUrl: avatar("Mikhail S", "D4A373", "0A1128"),
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-ru-03",
    firstName: "Ekaterina",
    lastName: "Novak",
    age: 28,
    gender: "FEMALE",
    country: "Rusia",
    city: "Novosibirsk",
    languages: ["ru", "en", "de"],
    profession: "Matemática",
    maritalStatus: "Single",
    bio: "Profesora universitaria de matemáticas. Contradictoriamente romántica y amante del arte impresionista. Me gustaría encontrar a alguien que equilibre mi mundo lógico.",
    interests: ["Matemáticas", "Arte", "Teatro", "Pilates"],
    height: 169,
    imageUrl: avatar("Ekaterina N", "A78BFA", "ffffff"),
    verified: false,
    lookingFor: "serious",
  },
  {
    id: "mock-ru-04",
    firstName: "Artem",
    lastName: "Petrov",
    age: 27,
    gender: "MALE",
    country: "Rusia",
    city: "Kazán",
    languages: ["ru", "en", "tt"],
    profession: "Músico",
    maritalStatus: "Single",
    bio: "Guitarrista de jazz y rock. He tocado en 12 países. Busco una conexión real, no solo swipes. El idioma es una barrera que la música derrita.",
    interests: ["Música", "Jazz", "Viajes", "Fotografía"],
    height: 178,
    imageUrl: avatar("Artem P", "38BDF8", "0A1128"),
    verified: true,
    lookingFor: "friendship",
  },
  {
    id: "mock-ru-05",
    firstName: "Natalia",
    lastName: "Kozlov",
    age: 31,
    gender: "FEMALE",
    country: "Rusia",
    city: "Sochi",
    languages: ["ru", "en"],
    profession: "Empresaria",
    maritalStatus: "Divorced",
    bio: "Dirigí mi primera empresa a los 25. Ahora busco equilibrio, aventura y quizás el amor. Me encantan el mar, los negocios y las personas ambiciosas.",
    interests: ["Negocios", "Mar", "Tenis", "Moda"],
    height: 172,
    imageUrl: avatar("Natalia K", "FB923C", "0A1128"),
    verified: true,
    lookingFor: "marriage",
  },

  // ─── LETONIA ─────────────────────────────────────────────────
  {
    id: "mock-lv-01",
    firstName: "Liga",
    lastName: "Berzins",
    age: 26,
    gender: "FEMALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "ru", "de"],
    profession: "Traductora",
    maritalStatus: "Single",
    bio: "Hablo 4 idiomas y aprendo el 5°: español. Riga es preciosa, pero sueño con el Mediterráneo. Busco un compañero de vida curioso y viajero.",
    interests: ["Idiomas", "Viajes", "Cocina", "Literatura"],
    height: 171,
    imageUrl: avatar("Liga B", "FF6B8B", "ffffff"),
    verified: true,
    lookingFor: "cultural",
  },
  {
    id: "mock-lv-02",
    firstName: "Andris",
    lastName: "Kalninsh",
    age: 33,
    gender: "MALE",
    country: "Letonia",
    city: "Jūrmala",
    languages: ["lv", "en", "ru"],
    profession: "Arquitecto Naval",
    maritalStatus: "Single",
    bio: "Diseño veleros de competición. El Báltico es mi casa pero el Mediterráneo es mi sueño. Busco una persona aventurera para navegar juntos por la vida.",
    interests: ["Vela", "Arquitectura", "Naturaleza", "Cocina escandinava"],
    height: 184,
    imageUrl: avatar("Andris K", "34D399", "0A1128"),
    verified: true,
    lookingFor: "serious",
  },
  {
    id: "mock-lv-03",
    firstName: "Marta",
    lastName: "Ozola",
    age: 23,
    gender: "FEMALE",
    country: "Letonia",
    city: "Daugavpils",
    languages: ["lv", "ru", "en"],
    profession: "Estudiante de Arte",
    maritalStatus: "Single",
    bio: "Estudio bellas artes y me especializo en cerámica. Me encanta conocer culturas nuevas y compartir el proceso creativo con personas apasionadas.",
    interests: ["Cerámica", "Arte contemporáneo", "Música folk", "Senderismo"],
    height: 162,
    imageUrl: avatar("Marta O", "C084FC", "ffffff"),
    verified: false,
    lookingFor: "friendship",
  },
  {
    id: "mock-lv-04",
    firstName: "Janis",
    lastName: "Liepins",
    age: 29,
    gender: "MALE",
    country: "Letonia",
    city: "Riga",
    languages: ["lv", "en", "ru", "es"],
    profession: "Programador",
    maritalStatus: "Single",
    bio: "Desarrollador fullstack que trabaja en remoto desde cualquier punto del mundo. Actualmente desde España. Me encanta el fútbol, la cerveza artesanal y el debate filosófico.",
    interests: ["Tecnología", "Fútbol", "Filosofía", "Viajes"],
    height: 179,
    imageUrl: avatar("Janis L", "D4A373", "0A1128"),
    verified: true,
    lookingFor: "relationship",
  },
  {
    id: "mock-lv-05",
    firstName: "Ilze",
    lastName: "Vitola",
    age: 35,
    gender: "FEMALE",
    country: "Letonia",
    city: "Liepāja",
    languages: ["lv", "en", "ru"],
    profession: "Médica",
    maritalStatus: "Single",
    bio: "Médica de urgencias. La vida me ha enseñado a valorar cada momento. Busco una relación seria con alguien que comparta mis valores y tenga sentido del humor.",
    interests: ["Medicina", "Yoga", "Lectura", "Cocina báltica"],
    height: 167,
    imageUrl: avatar("Ilze V", "FB923C", "0A1128"),
    verified: true,
    lookingFor: "marriage",
  },
];
