import { DatingProfile } from "../components/TinderCard";

export const mockProfiles: DatingProfile[] = [
  {
    id: "profile-1",
    firstName: "Svetlana",
    lastName: "Smirnova",
    age: 24,
    gender: "FEMALE",
    country: "Rusia",
    city: "Moscú",
    languages: ["ru", "en"],
    profession: "Diseñadora de Moda",
    maritalStatus: "Single",
    bio: "Me encanta viajar, la pintura clásica y la comida mediterránea. Busco conocer gente en España para aprender el idioma e intercambio cultural.",
    interests: ["Art", "Travel", "Cooking"],
    height: 172,
    imageUrl: "", // SVG fallback will trigger if empty, or we can use generic online placeholders
    verified: true,
  },
  {
    id: "profile-2",
    firstName: "Carlos",
    lastName: "Gómez",
    age: 29,
    gender: "MALE",
    country: "España",
    city: "Madrid",
    languages: ["es", "en"],
    profession: "Fotógrafo",
    maritalStatus: "Single",
    bio: "Apasionado por capturar momentos. Busco conexiones genuinas con personas de toda Europa. ¡Hablemos de música y cine!",
    interests: ["Photography", "Music", "Cinema"],
    height: 182,
    imageUrl: "",
    verified: true,
  },
  {
    id: "profile-3",
    firstName: "Olga",
    lastName: "Kovalenko",
    age: 27,
    gender: "FEMALE",
    country: "Ucrania",
    city: "Kiev",
    languages: ["ru", "en", "es"],
    profession: "Traductora",
    maritalStatus: "Single",
    bio: "Estudio español desde hace dos años. Me gustaría practicar y conocer personas interesantes de España para amistad o relación seria.",
    interests: ["Languages", "Literature", "Hiking"],
    height: 168,
    imageUrl: "",
    verified: false,
  },
  {
    id: "profile-4",
    firstName: "Asta",
    lastName: "Kazlauskas",
    age: 26,
    gender: "FEMALE",
    country: "Lituania",
    city: "Vilna",
    languages: ["en", "ru"],
    profession: "Arquitecta",
    maritalStatus: "Single",
    bio: "Amo la arquitectura medieval y los climas cálidos de España. Planeo visitar Barcelona pronto.",
    interests: ["Architecture", "Design", "Wine Tasting"],
    height: 175,
    imageUrl: "",
    verified: true,
  },
  {
    id: "profile-5",
    firstName: "Dmitry",
    lastName: "Ivanov",
    age: 31,
    gender: "MALE",
    country: "Rusia",
    city: "San Petersburgo",
    languages: ["ru", "en"],
    profession: "Ingeniero de Software",
    maritalStatus: "Single",
    bio: "Fanático del fitness y de las startups tecnológicas. Planeando mudarme a Málaga.",
    interests: ["Fitness", "Startups", "Beach Volley"],
    height: 188,
    imageUrl: "",
    verified: true,
  }
];
